export const lesson06Quiz = [
  {
    id: 1,
    question: "A user visits a banking website and sees a padlock icon in their browser. The browser verified the site's certificate against a trusted root CA. What infrastructure makes this trust chain possible?",
    options: [
      "VPN tunnel",
      "PKI (Public Key Infrastructure) - hierarchical certificate trust system with CAs, certificates, and verification processes",
      "Firewall rules",
      "DNS records"
    ],
    correct: 1,
    explanation: "PKI (Public Key Infrastructure) enables trust on the internet through hierarchical certificate verification. PKI components: (1) Certificate Authority (CA) - issues and signs certificates (VeriSign, DigiCert, Let's Encrypt), (2) Registration Authority (RA) - verifies identity before CA issues cert, (3) Digital Certificates - contains public key + identity + CA signature, (4) Certificate Revocation Lists (CRL) / OCSP - check if cert is revoked. Trust chain: Root CA (pre-installed in browsers/OS) → signs Intermediate CA → signs Website Certificate. Browser trusts root CA → trusts intermediate → trusts website. This hierarchy enables: secure web browsing, email encryption, code signing, VPN authentication. Without PKI, every website would need out-of-band trust establishment - impossible at internet scale."
  },
  {
    id: 2,
    question: "A company's SSL certificate expires, and customers see security warnings when visiting the website. What should be done to resolve this?",
    options: [
      "Tell customers to ignore the warning",
      "Renew the certificate before expiration - certificates have validity periods and must be renewed",
      "Switch to HTTP instead of HTTPS",
      "Restart the web server"
    ],
    correct: 1,
    explanation: "Certificate expiration requires RENEWAL - certificates intentionally have limited validity periods. Why certificates expire: (1) Limits damage if private key compromised, (2) Ensures periodic validation of identity, (3) Allows adoption of stronger algorithms, (4) Forces key rotation. Certificate validity periods: (1) Previously 2-3 years, (2) Current maximum: 398 days (13 months) for public certificates, (3) Let's Encrypt: 90 days (automation encouraged). Resolution: (1) Generate new CSR (Certificate Signing Request) or use existing key, (2) Submit to CA, complete validation, (3) Install new certificate before expiration. Best practices: (1) Track expiration dates, (2) Set renewal reminders (30+ days before), (3) Automate renewal where possible (Let's Encrypt/ACME), (4) Test new certificate before switching. Never tell users to ignore warnings - trains bad security habits and undermines trust."
  },
  {
    id: 3,
    question: "A server administrator generates a CSR (Certificate Signing Request) to obtain an SSL certificate. What does the CSR contain?",
    options: [
      "The private key for the certificate",
      "Public key and identifying information (domain, organization) to be certified by CA",
      "The CA's private key",
      "Encrypted website content"
    ],
    correct: 1,
    explanation: "A CSR (Certificate Signing Request) contains information needed for CA to issue a certificate. CSR contents: (1) PUBLIC key (NEVER private key!), (2) Subject information (domain name, organization, location), (3) Signature (proves you have corresponding private key). CSR process: (1) Generate key pair on server, (2) Create CSR with public key + identity info, (3) Send CSR to CA, (4) CA verifies identity (varies by cert type), (5) CA signs certificate, returns to you, (6) Install certificate on server. CRITICAL: Private key stays on YOUR server - never sent to CA, never shared. CA only sees public key. If CA required private key, they could impersonate you. CSR can be generated by: web server (Apache, Nginx), OpenSSL command line, Windows Server, hosting control panels."
  },
  {
    id: 4,
    question: "A company needs certificates for www.example.com, mail.example.com, and ftp.example.com. What type of certificate can secure ALL these subdomains with a single certificate?",
    options: [
      "Single-domain certificate",
      "Wildcard certificate (*.example.com) - covers all subdomains of a domain",
      "Code signing certificate",
      "Root CA certificate"
    ],
    correct: 1,
    explanation: "WILDCARD certificates secure a domain and ALL its subdomains with one certificate. Wildcard format: *.example.com covers: www.example.com, mail.example.com, ftp.example.com, anything.example.com. Limitations: (1) Only one level deep (*.example.com doesn't cover sub.www.example.com), (2) Doesn't cover base domain (example.com) - usually included as SAN, (3) Higher security risk if compromised (all subdomains affected). Alternative: SAN (Subject Alternative Name) certificate - lists specific domains/subdomains individually (more control, less flexibility). Wildcard benefits: (1) One certificate for multiple subdomains, (2) Easier management, (3) Cost-effective for many subdomains. Wildcard risks: (1) Private key compromise affects all subdomains, (2) Can't use different validation levels per subdomain. Choice depends on: number of subdomains, security requirements, management preferences."
  },
  {
    id: 5,
    question: "When a user's browser connects to a website, it checks whether the certificate has been revoked. The browser queries a service that responds with certificate status in real-time. What is this service called?",
    options: [
      "DNS server",
      "OCSP (Online Certificate Status Protocol) - real-time certificate revocation checking",
      "DHCP server",
      "Active Directory"
    ],
    correct: 1,
    explanation: "OCSP (Online Certificate Status Protocol) provides real-time certificate revocation status. How OCSP works: (1) Browser connects to website, receives certificate, (2) Browser queries CA's OCSP responder, (3) OCSP responder returns: Good, Revoked, or Unknown, (4) Browser decides whether to proceed. OCSP vs CRL: (1) CRL (Certificate Revocation List) - download entire list of revoked certs (large, periodic), (2) OCSP - query specific cert status (smaller, real-time). OCSP improvements: (1) OCSP Stapling - server queries OCSP, includes response with certificate (faster, more private), (2) Must-Staple - certificate requires stapled OCSP response. Privacy concern: traditional OCSP tells CA which sites you visit. OCSP stapling solves this. Revocation checking ensures: compromised or mis-issued certificates are rejected, CAs can invalidate certificates before expiration."
  },
  {
    id: 6,
    question: "A bank's website has a certificate showing the organization name in the browser's address bar, with extensive validation of the organization's legal identity. What type of certificate is this?",
    options: [
      "Domain Validated (DV) - basic validation",
      "Extended Validation (EV) - highest validation level with legal identity verification",
      "Self-signed certificate",
      "Wildcard certificate"
    ],
    correct: 1,
    explanation: "Extended Validation (EV) certificates require the most rigorous identity verification. Certificate validation levels: (1) DV (Domain Validation) - CA only verifies domain control (automated, minutes), (2) OV (Organization Validation) - CA verifies organization exists (days), (3) EV (Extended Validation) - CA verifies legal identity, physical location, operational status (weeks). EV requirements: (1) Verify legal existence, (2) Verify physical address, (3) Verify operational existence, (4) Verify identity of requester. EV indicators: historically showed organization name in green address bar (browsers have reduced this visibility). Use cases: banks, e-commerce, government - where users need high trust. Cost: DV (free to ~$100) < OV (~$100-500) < EV (~$200-1000+). All provide same encryption - difference is identity assurance level. Recent trend: browsers de-emphasize EV visual distinction, focusing on encryption presence."
  },
  {
    id: 7,
    question: "An administrator creates a certificate on their server without involving any external Certificate Authority. Users see 'untrusted certificate' warnings when connecting. What type of certificate is this?",
    options: [
      "Wildcard certificate",
      "Self-signed certificate - not signed by trusted CA, so browsers don't trust it by default",
      "Extended Validation certificate",
      "Code signing certificate"
    ],
    correct: 1,
    explanation: "SELF-SIGNED certificates are created and signed by the owner rather than a trusted CA. Characteristics: (1) Technically valid - provides encryption, (2) Not trusted by default - browsers show warnings, (3) No identity verification - anyone can create one claiming any identity. Why warnings occur: browsers trust certificates signed by CAs in their trust store. Self-signed certs aren't signed by those CAs → no trust chain → warning. Legitimate uses: (1) Internal/development environments, (2) Testing, (3) IoT devices on isolated networks, (4) When you control all clients (can add cert to trust store). NOT appropriate for: public websites, external users, production environments. Making self-signed trusted: (1) Add to trusted certificate store (each client), (2) Deploy via Group Policy (enterprise), (3) Or use proper CA-signed certificate. Self-signed are free and instant but sacrifice trust model."
  },
  {
    id: 8,
    question: "A certificate contains the fields: Subject: CN=www.example.com, Issuer: DigiCert CA, Valid From: 2024-01-01, Valid To: 2025-01-01, Public Key, and CA's Digital Signature. What standard defines this certificate format?",
    options: [
      "IEEE 802.11",
      "X.509 - standard format for digital certificates",
      "TCP/IP",
      "SMTP"
    ],
    correct: 1,
    explanation: "X.509 is the standard defining digital certificate format. X.509 certificate contents: (1) Version (v1, v2, v3), (2) Serial number (unique per CA), (3) Signature algorithm, (4) Issuer (CA that signed it), (5) Validity period (Not Before, Not After), (6) Subject (who cert is issued to), (7) Public key, (8) Extensions (v3) - key usage, SANs, constraints, (9) CA's digital signature. Common extensions: (1) Subject Alternative Name (SAN) - additional domains, (2) Key Usage - what key can be used for, (3) Basic Constraints - is this a CA certificate? X.509 is used in: HTTPS/TLS, email encryption (S/MIME), VPNs, code signing, document signing. Certificate file formats: PEM (Base64, common on Linux), DER (binary), PFX/P12 (includes private key), P7B (certificate chain). X.509 enables interoperability - any compliant system can read and verify certificates."
  },
  {
    id: 9,
    question: "A company's root CA is kept offline in a secure vault, never connected to the network. Day-to-day certificate issuance is done by an intermediate CA. Why is this architecture used?",
    options: [
      "Root CAs cannot issue certificates",
      "Protecting root CA - if compromised, entire trust chain fails; intermediate CAs limit exposure",
      "To slow down certificate issuance",
      "Root CAs are obsolete"
    ],
    correct: 1,
    explanation: "OFFLINE ROOT CA is a critical security practice - root CA compromise is catastrophic. Why protect root CA: (1) Root CA is the trust anchor - all certificates chain to it, (2) If root is compromised, attacker can issue any certificate, (3) Revoking root CA invalidates ALL certificates it issued, (4) Root CA private key is the most valuable target. Hierarchical architecture: (1) Root CA (offline) - signs intermediate CA certificates only, (2) Intermediate CA(s) (online) - issues end-entity certificates, (3) End-entity certificates - websites, users, devices. If intermediate CA compromised: (1) Revoke intermediate, (2) Issue new intermediate from root, (3) Re-issue affected certificates, (4) Trust chain recovers. If root compromised: entire PKI must be rebuilt. Offline root CA: powered on only to sign intermediate certificates (rare), air-gapped, physically secured, requires multiple persons (separation of duties)."
  },
  {
    id: 10,
    question: "A security analyst discovers a malicious website using a valid certificate for the company's domain. The certificate was issued by a CA after the attacker compromised DNS. What must the company do IMMEDIATELY?",
    options: [
      "Wait for certificate to expire",
      "Request certificate revocation from the CA - invalidate the fraudulent certificate immediately",
      "Change DNS providers",
      "Nothing, the certificate is valid"
    ],
    correct: 1,
    explanation: "Certificate REVOCATION is critical when certificates are compromised or mis-issued. Revocation process: (1) Contact issuing CA immediately, (2) Provide evidence of fraud/compromise, (3) CA adds certificate to CRL and updates OCSP, (4) Browsers checking revocation will reject the certificate. Revocation reasons: (1) Private key compromise, (2) Certificate mis-issuance (like this scenario), (3) Information change (company name, domain ownership), (4) CA compromise, (5) Certificate no longer needed. After revocation: (1) CRL updated (periodic), (2) OCSP responds 'Revoked' (immediate), (3) Browsers should reject certificate. Limitations: not all browsers check revocation by default, soft-fail means check failure doesn't block access. Additional actions: investigate DNS compromise, implement DNSSEC, consider Certificate Transparency monitoring (detect rogue certificate issuance). Also contact CA to understand how validation was bypassed."
  },
  {
    id: 11,
    question: "An organization wants to ensure they're notified if any CA anywhere in the world issues a certificate for their domain. What technology provides this visibility?",
    options: [
      "DNSSEC",
      "Certificate Transparency (CT) - public logs of all issued certificates enabling monitoring",
      "OCSP",
      "IPsec"
    ],
    correct: 1,
    explanation: "Certificate Transparency (CT) creates public, append-only logs of all certificates issued by participating CAs. How CT works: (1) CA submits certificate to CT logs before/during issuance, (2) Log returns Signed Certificate Timestamp (SCT), (3) Certificate includes SCT proving it's logged, (4) Anyone can search logs for certificates. Benefits: (1) Domain owners can monitor for unauthorized certificates, (2) Mis-issuance is publicly visible, (3) Rogue CAs can be detected, (4) Browsers can require CT (reject certs without SCT). Monitoring: services like crt.sh, Censys, SSLMate search CT logs. You can set alerts for your domains. CT was created after incidents where CAs mis-issued certificates (DigiNotar, Symantec). Now mandatory: browsers require CT for certificates to be trusted. Organizations should: monitor CT logs for their domains, investigate any unexpected certificates, implement CAA records to restrict which CAs can issue."
  },
  {
    id: 12,
    question: "A company stores SSL certificate private keys in a dedicated hardware device that prevents extraction and performs cryptographic operations internally. What is this device called?",
    options: [
      "SSD drive",
      "HSM (Hardware Security Module) - tamper-resistant device for key protection and crypto operations",
      "Network switch",
      "Backup server"
    ],
    correct: 1,
    explanation: "HSM (Hardware Security Module) provides secure key storage and cryptographic operations. HSM features: (1) Keys generated inside HSM, never leave in plain form, (2) Tamper-resistant hardware (detects physical attacks), (3) Performs crypto operations internally (signing, encryption), (4) FIPS 140-2/3 certified (government validation), (5) Role-based access control. Use cases: (1) CA private keys (especially root CA), (2) High-value SSL certificate keys, (3) Code signing keys, (4) Payment processing (PCI DSS), (5) Encryption key management. HSM types: (1) Network HSM - shared resource, accessed over network, (2) PCIe HSM - installed in server, (3) USB HSM - portable tokens, (4) Cloud HSM - cloud provider managed. Benefits: even if server is compromised, attacker can't extract keys. HSM can be destroyed/zeroed if physical theft attempted. Cost: $10,000 to $100,000+ for enterprise HSMs."
  },
  {
    id: 13,
    question: "An organization's private CA issues certificates for internal servers. Users on personal devices see certificate warnings because the private CA isn't trusted by default. What must be done?",
    options: [
      "The certificates are permanently untrusted",
      "Install the private CA's root certificate in device trust stores to establish trust",
      "Use weaker encryption",
      "Disable HTTPS"
    ],
    correct: 1,
    explanation: "Private/internal CAs require distributing their root certificate to establish trust. Solution process: (1) Export private CA's root certificate, (2) Install in client device's trusted root certificate store, (3) Device now trusts certificates issued by that CA. Distribution methods: (1) Group Policy (Windows domain) - automatic deployment, (2) MDM (Mobile Device Management) - managed phones/tablets, (3) Manual installation - user imports certificate, (4) System imaging - include in base image. Considerations: (1) Personal/BYOD devices need manual or MDM deployment, (2) Users must understand why they're trusting this CA, (3) Protect private CA - compromise allows issuing any certificate trusted by those devices. Alternative: use public CA (Let's Encrypt, etc.) for internal servers - avoids trust store management but requires DNS/public accessibility. Private CA benefits: no certificate costs, custom policies, no external dependencies."
  },
  {
    id: 14,
    question: "A certificate indicates 'Key Usage: Digital Signature, Key Encipherment' and 'Extended Key Usage: TLS Web Server Authentication'. What do these fields control?",
    options: [
      "Certificate expiration date",
      "Permitted uses of the certificate - restricts what cryptographic operations and purposes are allowed",
      "Certificate file format",
      "CA hierarchy level"
    ],
    correct: 1,
    explanation: "Key Usage and Extended Key Usage restrict certificate permitted operations. Key Usage (basic purposes): (1) Digital Signature - signing data, (2) Key Encipherment - encrypting keys for transport, (3) Data Encipherment - encrypting data, (4) Key Agreement - Diffie-Hellman, (5) Certificate Signing - only for CA certs, (6) CRL Signing - signing revocation lists. Extended Key Usage (specific applications): (1) TLS Web Server Authentication - HTTPS servers, (2) TLS Web Client Authentication - client certificates, (3) Code Signing - signing software, (4) Email Protection - S/MIME, (5) Time Stamping. Why restrictions matter: (1) Prevents certificate misuse, (2) Web server cert can't sign code, (3) Limits damage if compromised, (4) Compliance requirements. CA sets these during issuance. Applications/browsers enforce them - certificate for wrong purpose is rejected."
  },
  {
    id: 15,
    question: "A security team receives a certificate file with .pfx extension that contains both the certificate and private key, protected by a password. What is this format also known as?",
    options: [
      "PEM format",
      "PKCS#12 (P12) - format containing certificate with private key, password protected",
      "CRL format",
      "Plain text format"
    ],
    correct: 1,
    explanation: "PFX/P12 (PKCS#12) is a format containing certificate AND private key together, password-encrypted. Certificate file formats: (1) PEM (.pem, .crt, .cer) - Base64 encoded, 'BEGIN CERTIFICATE', common on Linux, (2) DER (.der, .cer) - binary format, common on Windows, (3) PFX/P12 (.pfx, .p12) - certificate + private key, password protected, (4) P7B (.p7b) - certificate chain only, no private key. Use cases for PFX/P12: (1) Transferring certificate with key between servers, (2) Importing to Windows servers (IIS), (3) Backup of certificate with key, (4) Browser certificate import. Security considerations: (1) Contains private key - treat as highly sensitive, (2) Password protect with strong password, (3) Transmit securely, (4) Delete after import when possible. Converting between formats: OpenSSL can convert (PEM to PFX, etc.). Knowing formats is essential for certificate management across different platforms."
  }
];